# Generated by Django 6.0.5 on 2026-06-07 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'aluno'}, related_name='turmas_aluno', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
