# Generated by Django 6.0.5 on 2026-06-09 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='administrador.turma')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='professor.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('corrigido', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'user_type': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='professor.atividade')),
            ],
        ),
    ]
