# Generated by Django 6.0.5 on 2026-06-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregaatividade',
            old_name='corrigido',
            new_name='corrigida',
        ),
    ]
