# Generated by Django 6.0.6 on 2026-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_rename_corrigido_entregaatividade_corrigida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterioatividade',
            name='palavra_chave',
        ),
        migrations.AddField(
            model_name='criterioatividade',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterioatividade',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=120),
            preserve_default=False,
        ),
    ]
